name: Semantic Release

on:
  push:
    branches:
      - main

concurrency:
  group: semantic-release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Enable Corepack
        run: npm i -g --force corepack@latest && corepack enable

      - name: Install dependencies
        run: npx nypm@latest i

      - name: Prepare dev environment
        run: npm run dev:prepare

      - name: Build
        run: npm run prepack

      - name: Test
        run: npm run test

      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
